In [2]:
# 1. Create a DataFrame

# Question: Create a DataFrame with Name
#  Age, City and Marks.
import pandas as pd

In [1]:
import pandas as pd

data = {
    "Name": ["Ravi", "Priya", "Kiran", "Anu"],
    "Age": [21, 22, 20, 23],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad"],
    "Marks": [85, 92, 78, 88],
    "percent":[85.0,92.0,78.0,88.0]
}

df = pd.DataFrame(data)


print(df)
df

    Name  Age       City  Marks  percent
0   Ravi   21  Hyderabad     85     85.0
1  Priya   22    Chennai     92     92.0
2  Kiran   20  Bangalore     78     78.0
3    Anu   23  Hyderabad     88     88.0

    Name  Age       City  Marks  percent
0   Ravi   21  Hyderabad     85     85.0
1  Priya   22    Chennai     92     92.0
2  Kiran   20  Bangalore     78     78.0
3    Anu   23  Hyderabad     88     88.0

In [3]:
# 2. Display first 2 rows

# Question: How do you display the first 2 rows?
print(df.head(2))

print(df.head(3))

    Name  Age       City  Marks  percent
0   Ravi   21  Hyderabad     85     85.0
1  Priya   22    Chennai     92     92.0
    Name  Age       City  Marks  percent
0   Ravi   21  Hyderabad     85     85.0
1  Priya   22    Chennai     92     92.0
2  Kiran   20  Bangalore     78     78.0

In [6]:
# 3. Display last 2 rows
print(df.tail(2))

print(df.tail(3))

    Name  Age       City  Marks  percent
2  Kiran   20  Bangalore     78     78.0
3    Anu   23  Hyderabad     88     88.0
    Name  Age       City  Marks  percent
1  Priya   22    Chennai     92     92.0
2  Kiran   20  Bangalore     78     78.0
3    Anu   23  Hyderabad     88     88.0

In [7]:
#   4. find the number of rows and columns
print(df.shape)


df.size

(4, 5)

20

In [9]:
# 5. Select one column
# Question: Display only Marks.
# q --> dispaly nams

print(df["Marks"])
print(df["Name"])

0    85
1    92
2    78
3    88
Name: Marks, dtype: int64
0     Ravi
1    Priya
2    Kiran
3      Anu
Name: Name, dtype: str

In [15]:
# 6. Select multiple columns
# Question: Display Name an
# d Marks
print(df[["Name", "Marks"]])
print(df[["Name","percent"]])

    Name  Marks
0   Ravi     85
1  Priya     92
2  Kiran     78
3    Anu     88
    Name  percent
0   Ravi     85.0
1  Priya     92.0
2  Kiran     78.0
3    Anu     88.0

In [16]:
# 7. Find students with marks greater than 80
print(df[df["Marks"] > 80])
print(df[(df["Marks"] > 80) & (df["percent"] <90)])

    Name  Age       City  Marks  percent
0   Ravi   21  Hyderabad     85     85.0
1  Priya   22    Chennai     92     92.0
3    Anu   23  Hyderabad     88     88.0
   Name  Age       City  Marks  percent
0  Ravi   21  Hyderabad     85     85.0
3   Anu   23  Hyderabad     88     88.0

In [17]:
# 8. Find students from Hyderabad
print(df[df["City"] == "Hyderabad"])

print(df[df["City"]=="Chennai"])

   Name  Age       City  Marks  percent
0  Ravi   21  Hyderabad     85     85.0
3   Anu   23  Hyderabad     88     88.0
    Name  Age     City  Marks  percent
1  Priya   22  Chennai     92     92.0

In [19]:
print(df["Age"])
print(df["percent"])

0    21
1    22
2    20
3    23
Name: Age, dtype: int64
0    85.0
1    92.0
2    78.0
3    88.0
Name: percent, dtype: float64

In [20]:
# 9. Find students older than 21
print(df[df["Age"]>21])

    Name  Age       City  Marks  percent
1  Priya   22    Chennai     92     92.0
3    Anu   23  Hyderabad     88     88.0

In [24]:
# 10. Find students with marks between 80 and 90
# Important: Pandas uses & for AND and | for OR.
print(df[(df["Marks"] >= 80) & (df["Marks"] <= 90)])

   Name  Age       City  Marks  percent
0  Ravi   21  Hyderabad     85     85.0
3   Anu   23  Hyderabad     88     88.0

In [1]:
#  11. Sort students by marks
print(df.sort_values('Marks'))

NameError: name 'df' is not defined

In [29]:
#  for highest marks first
print(df.sort_values("Marks",ascending=False))

    Name  Age       City  Marks  percent
1  Priya   22    Chennai     92     92.0
3    Anu   23  Hyderabad     88     88.0
0   Ravi   21  Hyderabad     85     85.0
2  Kiran   20  Bangalore     78     78.0

In [93]:
# 12. Find highest marks
print(df["Marks"].max())
#  13 --> find the  lowest marks
print(df["Marks"].min())
#  14. find the average marsk
print(df["Marks"].mean())
#  15. find the total marks
print(df["Marks"].sum())
# find the total  percent
print(df["percent"].sum())

92
78
85.75
343
343.0

In [94]:
# 16. Add a new column
# Question: Add a Result column.
df["result"] = df["Marks"] >=40
df

#  addd % column
df ["%"] = df["percent"] >=40
df

    Name  Age       City  Marks  percent  result     %
0   Ravi   21  Hyderabad     85     85.0    True  True
1  Priya   22    Chennai     92     92.0    True  True
2  Kiran   20  Bangalore     78     78.0    True  True
3    Anu   23  Hyderabad     88     88.0    True  True

In [95]:
# # 17. Create Pass/Fail column
df["result"] = df["Marks"].apply(
    lambda x: "pass" if x >= 40 else "fail"
)
print(df)

df["%"] = df["percent"].apply(
    lambda x: "pass" if x >=95 else "fail"
)
# print(df)
df

    Name  Age       City  Marks  percent result     %
0   Ravi   21  Hyderabad     85     85.0   pass  True
1  Priya   22    Chennai     92     92.0   pass  True
2  Kiran   20  Bangalore     78     78.0   pass  True
3    Anu   23  Hyderabad     88     88.0   pass  True

    Name  Age       City  Marks  percent result     %
0   Ravi   21  Hyderabad     85     85.0   pass  fail
1  Priya   22    Chennai     92     92.0   pass  fail
2  Kiran   20  Bangalore     78     78.0   pass  fail
3    Anu   23  Hyderabad     88     88.0   pass  fail

In [96]:
#  18 create a grade column
df["grade"] = df['Marks'].apply(
    lambda x : "A" if x >=90
    else "B" if x >=80
    else "C"
)
# print(df)
df

    Name  Age       City  Marks  percent result     % grade
0   Ravi   21  Hyderabad     85     85.0   pass  fail     B
1  Priya   22    Chennai     92     92.0   pass  fail     A
2  Kiran   20  Bangalore     78     78.0   pass  fail     C
3    Anu   23  Hyderabad     88     88.0   pass  fail     B

In [99]:
# 19. Find unique cities
print(df["City"] .unique)

print(df["Marks"].unique)
print(df["Marks"].unique())

<bound method Series.unique of 0    Hyderabad
1      Chennai
2    Bangalore
3    Hyderabad
Name: City, dtype: str>
<bound method Series.unique of 0    85
1    92
2    78
3    88
Name: Marks, dtype: int64>
[85 92 78 88]

In [102]:
# 20. Count students in each city
print(df["City"].value_counts())

City
Hyderabad    2
Chennai      1
Bangalore    1
Name: count, dtype: int64

In [104]:
# Advanced Pandas Questions
# 21. Use loc[]
# Question: Select students whose
# marks are greater than 80 and display Name + Marks.
print(df.loc[df["Marks"]> 80,["Name","Marks"]])

    Name  Marks
0   Ravi     85
1  Priya     92
3    Anu     88

In [105]:
# 22. Use iloc[]

# Question: Display first 2 rows and first 2 columns.
print(df.iloc[0:2,0:2])

    Name  Age
0   Ravi   21
1  Priya   22

In [106]:
# 23. Use query()

# Question: Find students whose marks are greater than 80.
print(df.query("Marks >80"))

    Name  Age       City  Marks  percent result     % grade
0   Ravi   21  Hyderabad     85     85.0   pass  fail     B
1  Priya   22    Chennai     92     92.0   pass  fail     A
3    Anu   23  Hyderabad     88     88.0   pass  fail     B

In [107]:
# Important: query() condition must match the column's data type.
# For example, if:
df.query("City == 'Hyderabad'")

   Name  Age       City  Marks  percent result     % grade
0  Ravi   21  Hyderabad     85     85.0   pass  fail     B
3   Anu   23  Hyderabad     88     88.0   pass  fail     B

In [30]:
# 24. Group by City
# Question: Find average marks for each city.
print(df.groupby("City")["Marks"].mean())
print(df.groupby("City")["Marks"].max())

City
Bangalore    78.0
Chennai      92.0
Hyderabad    86.5
Name: Marks, dtype: float64
City
Bangalore    78
Chennai      92
Hyderabad    88
Name: Marks, dtype: int64

In [49]:
# 25. Group by City and calculate multiple values
print(
    df.groupby("City")["Marks"].agg(["mean","max","min"])
)

           mean  max  min
City
Bangalore  78.0   78   78
Chennai    92.0   92   92
Hyderabad  86.5   88   85

In [51]:
# 26. Rename a column

df = df.rename(columns={"Marks": "Score"})

print(df)

    Name  Age       City  Score  percent result     % grade
0   Ravi   21  Hyderabad     85     85.0   pass  fail     B
1  Priya   22    Chennai     92     92.0   pass  fail     A
2  Kiran   20  Bangalore     78     78.0   pass  fail     C
3    Anu   23  Hyderabad     88     88.0   pass  fail     B

In [54]:
print(
    df.groupby("City")["Score"].agg(["mean","max","min"])
)

           mean  max  min
City
Bangalore  78.0   78   78
Chennai    92.0   92   92
Hyderabad  86.5   88   85

In [31]:
# remove column
df = df.drop(columns =["Age"])
print(df)

    Name       City  Marks  percent
0   Ravi  Hyderabad     85     85.0
1  Priya    Chennai     92     92.0
2  Kiran  Bangalore     78     78.0
3    Anu  Hyderabad     88     88.0

In [32]:
# 28. Find missing values
print(df.isnull().sum())

Name       0
City       0
Marks      0
percent    0
dtype: int64

In [38]:
df.columns = df.columns.str.strip()
print(df.columns.tolist())

['Name', 'City', 'Marks', 'percent']

In [39]:
# 29. Fill missing values
df["Marks"] = df["Marks"].fillna(0)
print(df)
df

    Name       City  Marks  percent
0   Ravi  Hyderabad     85     85.0
1  Priya    Chennai     92     92.0
2  Kiran  Bangalore     78     78.0
3    Anu  Hyderabad     88     88.0

    Name       City  Marks  percent
0   Ravi  Hyderabad     85     85.0
1  Priya    Chennai     92     92.0
2  Kiran  Bangalore     78     78.0
3    Anu  Hyderabad     88     88.0

In [61]:
#  30. remove duplicate rows
df = df.drop_duplicates()
# print(df)
df

    Name       City  Score  percent result     % grade
0   Ravi  Hyderabad     85     85.0   pass  fail     B
1  Priya    Chennai     92     92.0   pass  fail     A
2  Kiran  Bangalore     78     78.0   pass  fail     C
3    Anu  Hyderabad     88     88.0   pass  fail     B

In [5]:
df["Marks"].mean()
df["percent"].mean()

np.float64(85.75)

In [36]:
df.groupby("City")["percent"].mean()

City
Bangalore    78.0
Chennai      92.0
Hyderabad    86.5
Name: percent, dtype: float64

In [37]:
# (df["City"].nunique().count())
df["City"].mode()[0]

'Hyderabad'

In [40]:
print(df.columns.tolist())

['Name', 'City', 'Marks', 'percent']

In [48]:

df.groupby("City").agg({"Marks": ["sum", "mean"]})

          Marks
            sum  mean
City
Bangalore    78  78.0
Chennai      92  92.0
Hyderabad   173  86.5