In [31]:
import  pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\vadla\OneDrive\Desktop\excl flie\IPL_Matches_Data_2008_2026.csv")
df.head()

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
0,Indian Premier League,2007/08,1.0,18-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,RE Koertzen,AM Saheba,VN Kulkarni,T20,20,6,male,club,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey..."
1,Indian Premier League,2007/08,2.0,19-04-2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,...,SL Shastri,RB Tiffin,MSS Ranawat,T20,20,6,male,club,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ..."
2,Indian Premier League,2007/08,3.0,19-04-2008,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,...,GA Pratapkumar,IL Howell,Unknown,T20,20,6,male,club,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm..."
3,Indian Premier League,2007/08,4.0,20-04-2008,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,...,K Hariharan,Asad Rauf,F Gomes,T20,20,6,male,club,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S..."
4,Indian Premier League,2007/08,5.0,20-04-2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,DJ Harper,AV Jayaprakash,SN Bandekar,T20,20,6,male,club,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli..."

In [3]:
df.head()

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
0,Indian Premier League,2007/08,1.0,18-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,RE Koertzen,AM Saheba,VN Kulkarni,T20,20,6,male,club,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey..."
1,Indian Premier League,2007/08,2.0,19-04-2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,...,SL Shastri,RB Tiffin,MSS Ranawat,T20,20,6,male,club,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ..."
2,Indian Premier League,2007/08,3.0,19-04-2008,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,...,GA Pratapkumar,IL Howell,Unknown,T20,20,6,male,club,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm..."
3,Indian Premier League,2007/08,4.0,20-04-2008,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,...,K Hariharan,Asad Rauf,F Gomes,T20,20,6,male,club,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S..."
4,Indian Premier League,2007/08,5.0,20-04-2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,DJ Harper,AV Jayaprakash,SN Bandekar,T20,20,6,male,club,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli..."

In [33]:
df.tail()

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
1238,Indian Premier League,2026,70.0,24-05-2026,Kolkata,"Eden Gardens, Kolkata",Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,...,HAS Khalid,SJ Nogajski,M Krishnadas,T20,20,6,male,club,"Kuldeep Yadav, Abishek Porel, KL Rahul, SU Par...","SP Narine, AM Rahane, FH Allen, MK Pandey, C G..."
1239,Indian Premier League,2026,NaN,26-05-2026,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Royal Challengers Bengaluru,Gujarat Titans,Gujarat Titans,field,...,VK Sharma,Nitin Menon,KN Ananthapadmanabhan,T20,20,6,male,club,"R Shepherd, VR Iyer, V Kohli, D Padikkal, RM P...","K Khejroliya, B Sai Sudharsan, Shubman Gill, J..."
1240,Indian Premier League,2026,NaN,27-05-2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,...,UV Gandhe,R Pandit,SJ Nogajski,T20,20,6,male,club,"YBK Jaiswal, V Suryavanshi, Dhruv Jurel, R Par...","PP Hinge, Abhishek Sharma, TM Head, Ishan Kish..."
1241,Indian Premier League,2026,NaN,29-05-2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,bat,...,SJ Nogajski,AT Holdstock,UV Gandhe,T20,20,6,male,club,"TU Deshpande, YBK Jaiswal, V Suryavanshi, Dhru...","Mohammed Siraj, B Sai Sudharsan, Shubman Gill,..."
1242,Indian Premier League,2026,NaN,31-05-2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,...,Nitin Menon,J Madanagopal,VK Sharma,T20,20,6,male,club,"M Prasidh Krishna, B Sai Sudharsan, Shubman Gi...","JA Duffy, VR Iyer, V Kohli, D Padikkal, RM Pat..."

In [5]:
df["city"].value_counts()

city
Mumbai            187
Kolkata           107
Delhi             104
Chennai            98
Hyderabad          90
Jaipur             68
Bangalore          65
Chandigarh         61
Ahmedabad          53
Pune               51
Unknown            51
Bengaluru          39
Abu Dhabi          37
Lucknow            29
Dharamsala         19
Visakhapatnam      17
Durban             15
Dubai              13
Centurion          12
Rajkot             10
Sharjah            10
Indore              9
Navi Mumbai         9
Mohali              9
Johannesburg        8
Raipur              8
Guwahati            8
New Chandigarh      8
Cape Town           7
Port Elizabeth      7
Cuttack             7
Ranchi              7
Kochi               5
Kanpur              4
East London         3
Kimberley           3
Nagpur              3
Bloemfontein        2
Name: count, dtype: int64

In [6]:
df["city"].value_counts(ascending=True)

city
Bloemfontein        2
East London         3
Kimberley           3
Nagpur              3
Kanpur              4
Kochi               5
Cape Town           7
Port Elizabeth      7
Cuttack             7
Ranchi              7
Johannesburg        8
Raipur              8
Guwahati            8
New Chandigarh      8
Indore              9
Navi Mumbai         9
Mohali              9
Rajkot             10
Sharjah            10
Centurion          12
Dubai              13
Durban             15
Visakhapatnam      17
Dharamsala         19
Lucknow            29
Abu Dhabi          37
Bengaluru          39
Pune               51
Unknown            51
Ahmedabad          53
Chandigarh         61
Bangalore          65
Jaipur             68
Hyderabad          90
Chennai            98
Delhi             104
Kolkata           107
Mumbai            187
Name: count, dtype: int64

In [7]:
df[["event_name","season","match_number","date","city","venue","team1","team2","toss_winner","toss_decision"]]

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision
0,Indian Premier League,2007/08,1.0,18-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field
1,Indian Premier League,2007/08,2.0,19-04-2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat
2,Indian Premier League,2007/08,3.0,19-04-2008,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat
3,Indian Premier League,2007/08,4.0,20-04-2008,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat
4,Indian Premier League,2007/08,5.0,20-04-2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat
...,...,...,...,...,...,...,...,...,...,...
1238,Indian Premier League,2026,70.0,24-05-2026,Kolkata,"Eden Gardens, Kolkata",Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field
1239,Indian Premier League,2026,NaN,26-05-2026,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Royal Challengers Bengaluru,Gujarat Titans,Gujarat Titans,field
1240,Indian Premier League,2026,NaN,27-05-2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field
1241,Indian Premier League,2026,NaN,29-05-2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,bat
1242,Indian Premier League,2026,NaN,31-05-2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_name       1243 non-null   str
 1   season           1243 non-null   str
 2   match_number     1169 non-null   float64
 3   date             1243 non-null   str
 4   city             1243 non-null   str
 5   venue            1243 non-null   str
 6   team1            1243 non-null   str
 7   team2            1243 non-null   str
 8   toss_winner      1243 non-null   str
 9   toss_decision    1243 non-null   str
 10  team1_runs       1243 non-null   int64
 11  team1_wickets    1243 non-null   int64
 12  team2_runs       1243 non-null   int64
 13  team2_wickets    1243 non-null   int64
 14  winner           1218 non-null   str
 15  result_type      1243 non-null   str
 16  win_by_runs      1243 non-null   int64
 17  win_by_wickets   1243 non-null   int64
 18  player_of_match  1234 non-null   str
 19  match_referee    1243 non-null   str
 20  umpire1          1243 non-null   str
 21  umpire2          1243 non-null   str
 22  tv_umpire        1243 non-null   str
 23  reserve_umpire   1243 non-null   str
 24  match_type       1243 non-null   str
 25  overs_limit      1243 non-null   int64
 26  balls_per_over   1243 non-null   int64
 27  gender           1243 non-null   str
 28  team_type        1243 non-null   str
 29  team1_players    1243 non-null   str
 30  team2_players    1243 non-null   str
dtypes: float64(1), int64(8), str(22)
memory usage: 301.2 KB

In [14]:
df.shape

(1243, 31)

In [15]:
df.size

38533

In [21]:
df.describe()

,match_number,team1_runs,team1_wickets,team2_runs,team2_wickets,win_by_runs,win_by_wickets,overs_limit,balls_per_over
count,1169.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.0,1243.0
mean,31.921300,165.851167,5.956557,157.349155,5.873693,13.932422,3.276750,20.0,6.0
std,18.626023,35.490847,2.309341,34.613073,2.646538,23.861556,3.358216,0.0,0.0
min,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.0,6.0
25%,16.000000,144.000000,4.000000,138.000000,4.000000,0.000000,0.000000,20.0,6.0
50%,32.000000,165.000000,6.000000,160.000000,6.000000,0.000000,3.000000,20.0,6.0
75%,47.000000,189.000000,8.000000,179.000000,8.000000,20.000000,6.000000,20.0,6.0
max,72.000000,287.000000,10.000000,265.000000,12.000000,146.000000,10.000000,20.0,6.0

In [18]:
df.describe(include="all")

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
count,1243,1243,1169.000000,1243,1243,1243,1243,1243,1243,1243,...,1243,1243,1243,1243,1243.0,1243.0,1243,1243,1243,1243
unique,1,19,NaN,947,38,60,19,19,19,2,...,71,85,82,1,NaN,NaN,1,1,1225,1223
top,Indian Premier League,2013,NaN,19-04-2008,Mumbai,Eden Gardens,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,...,S Ravi,AK Chaudhary,K Srinivasan,T20,NaN,NaN,male,club,"JH Kallis, W Jaffer, RV Uthappa, R Dravid, V K...","YS Chahal, Priyansh Arya, P Simran Singh, C Co..."
freq,1243,76,NaN,2,187,77,142,152,160,825,...,83,73,60,1243,NaN,NaN,1243,1243,2,4
mean,NaN,NaN,31.921300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.0,6.0,NaN,NaN,NaN,NaN
std,NaN,NaN,18.626023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.0,6.0,NaN,NaN,NaN,NaN
25%,NaN,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.0,6.0,NaN,NaN,NaN,NaN
50%,NaN,NaN,32.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.0,6.0,NaN,NaN,NaN,NaN
75%,NaN,NaN,47.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.0,6.0,NaN,NaN,NaN,NaN
max,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.0,6.0,NaN,NaN,NaN,NaN

In [20]:
df.sample(5)

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
1219,Indian Premier League,2026,51.0,08-05-2026,Delhi,"Arun Jaitley Stadium, Delhi",Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,...,R Pandit,KM Gandhi,TM Srivastava,T20,20,6,male,club,"Kuldeep Yadav, P Nissanka, KL Rahul, N Rana, S...","CV Varun, AM Rahane, FH Allen, A Raghuvanshi, ..."
907,Indian Premier League,2022,32.0,20-04-2022,Mumbai,"Brabourne Stadium, Mumbai",Punjab Kings,Delhi Capitals,Delhi Capitals,field,...,Tapan Sharma,AK Chaudhary,R Pandit,T20,20,6,male,club,"MA Agarwal, S Dhawan, JM Bairstow, LS Livingst...","PP Shaw, DA Warner, SN Khan, RR Pant, R Powell..."
807,Indian Premier League,2020/21,52.0,31-10-2020,Unknown,Sharjah Cricket Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,...,K Srinivasan,C Shamshuddin,VA Kulkarni,T20,20,6,male,club,"JR Philippe, D Padikkal, V Kohli, AB de Villie...","DA Warner, WP Saha, MK Pandey, KS Williamson, ..."
480,Indian Premier League,2015,23.0,25-04-2015,Mumbai,Wankhede Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,...,CB Gaffaney,SD Fry,CK Nandan,T20,20,6,male,club,"LMP Simmons, PA Patel, UBT Chand, RG Sharma, K...","S Dhawan, DA Warner, KL Rahul, NV Ojha, RS Bop..."
1012,Indian Premier League,2023,63.0,16-05-2023,Lucknow,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Mumbai Indians,Mumbai Indians,field,...,A Nand Kishore,CB Gaffaney,M Krishnadas,T20,20,6,male,club,"Yash Thakur, DJ Hooda, Q de Kock, PN Mankad, K...","Akash Madhwal, Ishan Kishan, RG Sharma, SA Yad..."

In [39]:
df.isnull().sum()

event_name          0
season              0
match_number       74
date                0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets       0
team2_runs          0
team2_wickets       0
winner             25
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     9
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
match_type          0
overs_limit         0
balls_per_over      0
gender              0
team_type           0
team1_players       0
team2_players       0
dtype: int64

data cleaning

<!--  data cleaning -->

In [46]:
df["match_number"]=df["match_number"].fillna("unkonwn")

In [45]:
df["player_of_match"]= df["player_of_match"].fillna("no award")

In [47]:
df["winner "] = df["winner"].fillna("no result")

In [48]:
df.isnull().sum()

event_name          0
season              0
match_number        0
date                0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets       0
team2_runs          0
team2_wickets       0
winner             25
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     0
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
match_type          0
overs_limit         0
balls_per_over      0
gender              0
team_type           0
team1_players       0
team2_players       0
winner              0
dtype: int64

In [49]:
df= df.drop(columns= ["umpire1","umpire2"],errors="ignore")

In [50]:
df.head()

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players,winner
0,Indian Premier League,2007/08,1.0,18-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,AM Saheba,VN Kulkarni,T20,20,6,male,club,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",Kolkata Knight Riders
1,Indian Premier League,2007/08,2.0,19-04-2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,...,RB Tiffin,MSS Ranawat,T20,20,6,male,club,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",Chennai Super Kings
2,Indian Premier League,2007/08,3.0,19-04-2008,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,...,IL Howell,Unknown,T20,20,6,male,club,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...",Delhi Daredevils
3,Indian Premier League,2007/08,4.0,20-04-2008,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,...,Asad Rauf,F Gomes,T20,20,6,male,club,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...",Kolkata Knight Riders
4,Indian Premier League,2007/08,5.0,20-04-2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,AV Jayaprakash,SN Bandekar,T20,20,6,male,club,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...",Royal Challengers Bangalore

matches per season

In [51]:
df["season"].value_counts().sort_index()

season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    60
2021       60
2022       74
2023       74
2024       71
2025       74
2026       74
Name: count, dtype: int64

most successful teams

In [52]:
df["winner"].value_counts()

winner
Mumbai Indians                 155
Chennai Super Kings            148
Kolkata Knight Riders          140
Rajasthan Royals               123
Royal Challengers Bangalore    114
Sunrisers Hyderabad            102
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  58
Gujarat Titans                  47
Punjab Kings                    41
Lucknow Super Giants            34
Deccan Chargers                 29
Royal Challengers Bengaluru     29
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [53]:
#  how many matches  ended with no results
(df["winner"]== "No results").sum()

np.int64(0)

In [58]:
#  toss decisions -does winning  toss matter?
toss_match = (df["toss_winner"] == df["winner"]).sum()
toss_match

np.int64(628)

In [64]:
total_matches = df.shape[0]
round((toss_match/total_matches) * 100)

51

In [67]:
#  player of the match analysis
df["player_of_match"].value_counts().head(10)

player_of_match
AB de Villiers    25
CH Gayle          22
V Kohli           22
RG Sharma         21
MS Dhoni          18
DA Warner         18
SP Narine         18
RA Jadeja         17
KL Rahul          17
SR Watson         16
Name: count, dtype: int64

In [69]:
#  common  toss decisions(bat/ball)
df["toss_decision"].value_counts()

toss_decision
field    825
bat      418
Name: count, dtype: int64

In [77]:
# which team are the most succesuful at a perticular veanue ex -- m.chinaswamy stadium
venue = "M Chinnaswamy Stadium"
venue_wins = df[df["venue"] == venue]["winner"].value_counts()
venue_wins

winner
Royal Challengers Bangalore    28
Mumbai Indians                  8
Kolkata Knight Riders           6
Kings XI Punjab                 5
Chennai Super Kings             4
Rajasthan Royals                3
Delhi Daredevils                3
Sunrisers Hyderabad             2
Deccan Chargers                 1
Rising Pune Supergiant          1
Gujarat Lions                   1
Name: count, dtype: int64

In [78]:
venue = "Wankhede Stadium"
venue_wins = df[df["venue"] == venue]["winner"].value_counts()
venue_wins

winner
Mumbai Indians                 41
Chennai Super Kings             7
Kings XI Punjab                 5
Rajasthan Royals                4
Royal Challengers Bangalore     3
Delhi Daredevils                2
Rising Pune Supergiant          2
Kochi Tuskers Kerala            1
Deccan Chargers                 1
Pune Warriors                   1
Kolkata Knight Riders           1
Rising Pune Supergiants         1
Gujarat Lions                   1
Sunrisers Hyderabad             1
Delhi Capitals                  1
Name: count, dtype: int64

In [89]:
df["venue"].dropna().unique()

<StringArray>
[                                                  'M Chinnaswamy Stadium',
                              'Punjab Cricket Association Stadium, Mohali',
                                                        'Feroz Shah Kotla',
                                                            'Eden Gardens',
                                                        'Wankhede Stadium',
                                                  'Sawai Mansingh Stadium',
                               'Rajiv Gandhi International Stadium, Uppal',
                                         'MA Chidambaram Stadium, Chepauk',
                                              'Dr DY Patil Sports Academy',
                                                                'Newlands',
                                                        'St George's Park',
                                                               'Kingsmead',
                                                         'SuperSport Park',
                                                            'Buffalo Park',
                                                   'New Wanderers Stadium',
                                                   'De Beers Diamond Oval',
                                                         'OUTsurance Oval',
                                                       'Brabourne Stadium',
                                            'Sardar Patel Stadium, Motera',
                                                        'Barabati Stadium',
                                               'Brabourne Stadium, Mumbai',
                            'Vidarbha Cricket Association Stadium, Jamtha',
                            'Himachal Pradesh Cricket Association Stadium',
                                                           'Nehru Stadium',
                                                  'Holkar Cricket Stadium',
                     'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
                                              'Subrata Roy Sahara Stadium',
                                 'Maharashtra Cricket Association Stadium',
                        'Shaheed Veer Narayan Singh International Stadium',
                                      'JSCA International Stadium Complex',
                                                    'Sheikh Zayed Stadium',
                                                 'Sharjah Cricket Stadium',
                                     'Dubai International Cricket Stadium',
                    'Punjab Cricket Association IS Bindra Stadium, Mohali',
                                  'Saurashtra Cricket Association Stadium',
                                                              'Green Park',
                                                   'M.Chinnaswamy Stadium',
                            'Punjab Cricket Association IS Bindra Stadium',
                                      'Rajiv Gandhi International Stadium',
                                                  'MA Chidambaram Stadium',
                                                    'Arun Jaitley Stadium',
                                'MA Chidambaram Stadium, Chepauk, Chennai',
                                                'Wankhede Stadium, Mumbai',
                                        'Narendra Modi Stadium, Ahmedabad',
                                             'Arun Jaitley Stadium, Delhi',
                                        'Zayed Cricket Stadium, Abu Dhabi',
                                      'Dr DY Patil Sports Academy, Mumbai',
                           'Maharashtra Cricket Association Stadium, Pune',
                                                   'Eden Gardens, Kolkata',
        'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
   'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
                    'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
                                        'M Chinnaswamy Stadium, Bengaluru',
                                     'Barsapara Cricket Stadium, Guwahati',
                                          'Sawai Mansingh Stadium, Jaipur',
                'Himachal Pradesh Cricket Association Stadium, Dharamsala',
      'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
      'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
 'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh',
                'Shaheed Veer Narayan Singh International Stadium, Raipur']
Length: 60, dtype: str

In [117]:
#  which mathes ended with the largest margins?
df[df["win_by_runs"] >0].sort_values(by="win_by_runs",ascending=False).head(1)

# print("Largest winning margin:", largest_margin["win_by_runs"].iloc[0], "runs")
print(df["win_by_runs"].max())
print(df["win_by_wickets"].max())

146
10

In [115]:
#  which mathes ended with the  smalest margins?

df[df["win_by_runs"] >0].sort_values(by="win_by_runs",ascending=True).head(1)
print(df["win_by_runs"].min())
print(df["win_by_wickets"].min())

0
0

In [122]:
#  how many matches were decided by dls(duckworh -lewis) method
# df["method"].notnull.sum()
print(df["result_type"].value_counts())
df[df["result_type"].str.contains("DLS", case=False, na=False)]

result_type
complete     1218
tie            16
no result       9
Name: count, dtype: int64

Empty DataFrame
Columns: [event_name, season, match_number, date, city, venue, team1, team2, toss_winner, toss_decision, team1_runs, team1_wickets, team2_runs, team2_wickets, winner, result_type, win_by_runs, win_by_wickets, player_of_match, match_referee, tv_umpire, reserve_umpire, match_type, overs_limit, balls_per_over, gender, team_type, team1_players, team2_players, winner ]
Index: []

[0 rows x 30 columns]