In [ ]:
import pandas as pd

In [ ]:
#   series what is pandas series
#  a series  is a an daimentianal data structure think of its a single column of data with labesls (index). 
#  it stores of values
#  an index (automatically assingned unless you specify it)

# createating a series from a list
marks = pd.Series([85,90,75])
print(marks)

#  0,1,2 --> are the index labels.
#  85,90,75 --> are the actual data values.

0    85
1    90
2    75
dtype: int64

In [ ]:
# #  what is data frame 
# #  a data frame is a two daimesional table -like an excl sheet
# it contains :
#     * rows and columns
#     * each column is like a series
#     * you can have multiple seriesncominied into a data frame 

data  = {
    "name":  ["john","smith","joe"],
    "marks": [85,90,75]
}
df = pd.DataFrame(data)
print(df)

    name  marks
0   john     85
1  smith     90
2    joe     75

In [ ]:
import os 
print(os.getcwd())

c:\Users\vadla\OneDrive\Desktop\python.py

In [5]:
df

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
0,Indian Premier League,2007/08,1.0,18-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,RE Koertzen,AM Saheba,VN Kulkarni,T20,20,6,male,club,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey..."
1,Indian Premier League,2007/08,2.0,19-04-2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,...,SL Shastri,RB Tiffin,MSS Ranawat,T20,20,6,male,club,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ..."
2,Indian Premier League,2007/08,3.0,19-04-2008,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,...,GA Pratapkumar,IL Howell,Unknown,T20,20,6,male,club,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm..."
3,Indian Premier League,2007/08,4.0,20-04-2008,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,...,K Hariharan,Asad Rauf,F Gomes,T20,20,6,male,club,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S..."
4,Indian Premier League,2007/08,5.0,20-04-2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,DJ Harper,AV Jayaprakash,SN Bandekar,T20,20,6,male,club,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,Indian Premier League,2026,70.0,24-05-2026,Kolkata,"Eden Gardens, Kolkata",Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,...,HAS Khalid,SJ Nogajski,M Krishnadas,T20,20,6,male,club,"Kuldeep Yadav, Abishek Porel, KL Rahul, SU Par...","SP Narine, AM Rahane, FH Allen, MK Pandey, C G..."
1239,Indian Premier League,2026,NaN,26-05-2026,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Royal Challengers Bengaluru,Gujarat Titans,Gujarat Titans,field,...,VK Sharma,Nitin Menon,KN Ananthapadmanabhan,T20,20,6,male,club,"R Shepherd, VR Iyer, V Kohli, D Padikkal, RM P...","K Khejroliya, B Sai Sudharsan, Shubman Gill, J..."
1240,Indian Premier League,2026,NaN,27-05-2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,...,UV Gandhe,R Pandit,SJ Nogajski,T20,20,6,male,club,"YBK Jaiswal, V Suryavanshi, Dhruv Jurel, R Par...","PP Hinge, Abhishek Sharma, TM Head, Ishan Kish..."
1241,Indian Premier League,2026,NaN,29-05-2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,bat,...,SJ Nogajski,AT Holdstock,UV Gandhe,T20,20,6,male,club,"TU Deshpande, YBK Jaiswal, V Suryavanshi, Dhru...","Mohammed Siraj, B Sai Sudharsan, Shubman Gill,..."
1242,Indian Premier League,2026,NaN,31-05-2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,...,Nitin Menon,J Madanagopal,VK Sharma,T20,20,6,male,club,"M Prasidh Krishna, B Sai Sudharsan, Shubman Gi...","JA Duffy, VR Iyer, V Kohli, D Padikkal, RM Pat..."

In [12]:
import pandas as pd
data  = {
    "name":  ["john","smith","joe"],
    "marks": [85,90,75]
}
df = pd.DataFrame(data)
print(df)

    name  marks
0   john     85
1  smith     90
2    joe     75

In [13]:
df .tail()
df.head()

    name  marks
0   john     85
1  smith     90
2    joe     75

In [14]:
df.sample()

  name  marks
2  joe     75

In [18]:
data = [["a",1,2],["b",3,4],["c",5,6]]
list_df = pd.DataFrame(data)
list_df

   0  1  2
0  a  1  2
1  b  3  4
2  c  5  6

In [92]:
df.head(1)
df.tail(2)

    name  marks
1  smith     90
2    joe     75

In [93]:
df.sample()

    name  marks
1  smith     90

In [96]:
print(df.columns)

Index(['name', 'marks'], dtype='str')

In [97]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [20]:
df.info()
df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   marks   3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

        name      marks
count      3   3.000000
unique     3        NaN
top     john        NaN
freq       1        NaN
mean     NaN  83.333333
std      NaN   7.637626
min      NaN  75.000000
25%      NaN  80.000000
50%      NaN  85.000000
75%      NaN  87.500000
max      NaN  90.000000

In [30]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Ravi", "Sita", "Arjun", "Priya", "Ravi", "Kiran", "Anu", "Sita", "Rahul", None],
    "Age": [22, 24, 21, 25, 22, 23, None, 24, 26, 25],
    "City": ["Hyderabad", "Kurnool", "Hyderabad", "Vijayawada", "Hyderabad",
             "Kurnool", "Guntur", "Kurnool", "Guntur", None],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Male", "Female", "Female", "Male", "Female"],
    "Marks": [85, 92, 76, 88, 85, None, 95, 92, 67, 80],
    "Salary": [30000, 35000, 28000, 40000, 30000, 32000, 45000, 35000, 27000, 31000]
})

print(df)
df

    Name   Age        City  Gender  Marks  Salary
0   Ravi  22.0   Hyderabad    Male   85.0   30000
1   Sita  24.0     Kurnool  Female   92.0   35000
2  Arjun  21.0   Hyderabad    Male   76.0   28000
3  Priya  25.0  Vijayawada  Female   88.0   40000
4   Ravi  22.0   Hyderabad    Male   85.0   30000
5  Kiran  23.0     Kurnool    Male    NaN   32000
6    Anu   NaN      Guntur  Female   95.0   45000
7   Sita  24.0     Kurnool  Female   92.0   35000
8  Rahul  26.0      Guntur    Male   67.0   27000
9    NaN  25.0         NaN  Female   80.0   31000

    Name   Age        City  Gender  Marks  Salary
0   Ravi  22.0   Hyderabad    Male   85.0   30000
1   Sita  24.0     Kurnool  Female   92.0   35000
2  Arjun  21.0   Hyderabad    Male   76.0   28000
3  Priya  25.0  Vijayawada  Female   88.0   40000
4   Ravi  22.0   Hyderabad    Male   85.0   30000
5  Kiran  23.0     Kurnool    Male    NaN   32000
6    Anu   NaN      Guntur  Female   95.0   45000
7   Sita  24.0     Kurnool  Female   92.0   35000
8  Rahul  26.0      Guntur    Male   67.0   27000
9    NaN  25.0         NaN  Female   80.0   31000

In [31]:
#  size
df.size
# shape 
df.shape

(10, 6)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      str
 1   Age     9 non-null      float64
 2   City    9 non-null      str
 3   Gender  10 non-null     str
 4   Marks   9 non-null      float64
 5   Salary  10 non-null     int64
dtypes: float64(2), int64(1), str(3)
memory usage: 612.0 bytes

In [34]:
df.describe()

             Age      Marks       Salary
count   9.000000   9.000000     10.00000
mean   23.555556  84.444444  33300.00000
std     1.666667   8.903807   5618.42208
min    21.000000  67.000000  27000.00000
25%    22.000000  80.000000  30000.00000
50%    24.000000  85.000000  31500.00000
75%    25.000000  92.000000  35000.00000
max    26.000000  95.000000  45000.00000

In [38]:
df["Name"].value_counts(ascending=True)[:]

Name
Arjun    1
Priya    1
Kiran    1
Anu      1
Rahul    1
Ravi     2
Sita     2
Name: count, dtype: int64

In [51]:
#  selecting  multiple columns
df[["Name","City","Marks"]]

    Name        City  Marks
0   Ravi   Hyderabad   85.0
1   Sita     Kurnool   92.0
2  Arjun   Hyderabad   76.0
3  Priya  Vijayawada   88.0
4   Ravi   Hyderabad   85.0
5  Kiran     Kurnool    NaN
6    Anu      Guntur   95.0
7   Sita     Kurnool   92.0
8  Rahul      Guntur   67.0
9    NaN         NaN   80.0

In [52]:
#  selecting  multiple columns
df[["Salary","City","Marks","Name"]].agg({"Name":"max","Marks":"mean","City":"min","Salary":"max"})

Name           Sita
Marks     84.444444
City         Guntur
Salary        45000
dtype: object

In [59]:
#  row slicing
# df[["Name"]]
df[0:3]

    Name   Age       City  Gender  Marks  Salary
0   Ravi  22.0  Hyderabad    Male   85.0   30000
1   Sita  24.0    Kurnool  Female   92.0   35000
2  Arjun  21.0  Hyderabad    Male   76.0   28000

In [61]:
#  indexing .loc
df.loc[2,"Name"]
#  multiple columns
df.loc[2,["Name","City","Marks"]]

Name         Arjun
City     Hyderabad
Marks         76.0
Name: 2, dtype: object

In [63]:
#  iloc --> position bassed selection
df.iloc[0,3]

#  row positions 2 columns
df.iloc[0:3,0:1]

    Name
0   Ravi
1   Sita
2  Arjun

In [65]:
df[(df["Marks"] > 80) & (df["Age"] > 22)]

    Name   Age        City  Gender  Marks  Salary
1   Sita  24.0     Kurnool  Female   92.0   35000
3  Priya  25.0  Vijayawada  Female   88.0   40000
7   Sita  24.0     Kurnool  Female   92.0   35000

In [67]:
#  or
df[(df["City"] == "Hyderabad") | (df["City"] == "Kurnool")]

    Name   Age       City  Gender  Marks  Salary
0   Ravi  22.0  Hyderabad    Male   85.0   30000
1   Sita  24.0    Kurnool  Female   92.0   35000
2  Arjun  21.0  Hyderabad    Male   76.0   28000
4   Ravi  22.0  Hyderabad    Male   85.0   30000
5  Kiran  23.0    Kurnool    Male    NaN   32000
7   Sita  24.0    Kurnool  Female   92.0   35000

In [74]:
#  not
df[~(df["City"] == "Hyderabad")]

    Name   Age        City  Gender  Marks  Salary
1   Sita  24.0     Kurnool  Female   92.0   35000
3  Priya  25.0  Vijayawada  Female   88.0   40000
5  Kiran  23.0     Kurnool    Male    NaN   32000
6    Anu   NaN      Guntur  Female   95.0   45000
7   Sita  24.0     Kurnool  Female   92.0   35000
8  Rahul  26.0      Guntur    Male   67.0   27000
9    NaN  25.0         NaN  Female   80.0   31000

In [75]:
#  betwwwen
df[df["Marks"].between(70,80)]

    Name   Age       City  Gender  Marks  Salary
2  Arjun  21.0  Hyderabad    Male   76.0   28000
9    NaN  25.0        NaN  Female   80.0   31000

In [76]:
# is in() -->
df[df["City"].isin(["Hyderabad","Kurnool"])]

    Name   Age       City  Gender  Marks  Salary
0   Ravi  22.0  Hyderabad    Male   85.0   30000
1   Sita  24.0    Kurnool  Female   92.0   35000
2  Arjun  21.0  Hyderabad    Male   76.0   28000
4   Ravi  22.0  Hyderabad    Male   85.0   30000
5  Kiran  23.0    Kurnool    Male    NaN   32000
7   Sita  24.0    Kurnool  Female   92.0   35000

In [90]:
#  frequerence
#  value count --> counts how mant times each city occers
df["City"].value_counts()

City
Hyderabad     3
Kurnool       3
Guntur        2
Vijayawada    1
Name: count, dtype: int64

In [92]:
#  dont sort frequency
df["City"].value_counts(sort=False)

City
Hyderabad     3
Kurnool       3
Vijayawada    1
Guntur        2
Name: count, dtype: int64

In [95]:
# lowest frequency
df["City"].value_counts(ascending=True)

City
Vijayawada    1
Guntur        2
Hyderabad     3
Kurnool       3
Name: count, dtype: int64

In [133]:
#  include missing values
df["City"].value_counts(dropna = False)

City
Hyderabad     3
Kurnool       3
Guntur        2
Vijayawada    1
NaN           1
Name: count, dtype: int64

In [98]:
# proportion
df["City"].value_counts(normalize=True)

City
Hyderabad     0.333333
Kurnool       0.333333
Guntur        0.222222
Vijayawada    0.111111
Name: proportion, dtype: float64

In [100]:
#  percentage
df["City"].value_counts(normalize=True) *100

City
Hyderabad     33.333333
Kurnool       33.333333
Guntur        22.222222
Vijayawada    11.111111
Name: proportion, dtype: float64

In [101]:
#  unique()
df["City"].unique()
# df["City"].unique

<StringArray>
['Hyderabad', 'Kurnool', 'Vijayawada', 'Guntur', nan]
Length: 5, dtype: str

In [102]:
# #  nunique() --> count unique cityes
df["City"].nunique()
# df["City"].nunique

4

In [105]:
#  sorting  --> descending --> highest marks first
df.sort_values("Marks",ascending=False)

    Name   Age        City  Gender  Marks  Salary
6    Anu   NaN      Guntur  Female   95.0   45000
7   Sita  24.0     Kurnool  Female   92.0   35000
1   Sita  24.0     Kurnool  Female   92.0   35000
3  Priya  25.0  Vijayawada  Female   88.0   40000
0   Ravi  22.0   Hyderabad    Male   85.0   30000
4   Ravi  22.0   Hyderabad    Male   85.0   30000
9    NaN  25.0         NaN  Female   80.0   31000
2  Arjun  21.0   Hyderabad    Male   76.0   28000
8  Rahul  26.0      Guntur    Male   67.0   27000
5  Kiran  23.0     Kurnool    Male    NaN   32000

In [109]:
#  asending --> lowest marks first
df.sort_values("Marks",ascending=True)

    Name   Age        City  Gender  Marks  Salary
8  Rahul  26.0      Guntur    Male   67.0   27000
2  Arjun  21.0   Hyderabad    Male   76.0   28000
9    NaN  25.0         NaN  Female   80.0   31000
4   Ravi  22.0   Hyderabad    Male   85.0   30000
0   Ravi  22.0   Hyderabad    Male   85.0   30000
3  Priya  25.0  Vijayawada  Female   88.0   40000
7   Sita  24.0     Kurnool  Female   92.0   35000
1   Sita  24.0     Kurnool  Female   92.0   35000
6    Anu   NaN      Guntur  Female   95.0   45000
5  Kiran  23.0     Kurnool    Male    NaN   32000

In [145]:

#  multiple columns sorting
df.sort_values(["City","Marks"],ascending=[True,False])

    Name   Age        City  Gender  Marks  Salary
6    Anu   NaN      Guntur  Female   95.0   45000
8  Rahul  26.0      Guntur    Male   67.0   27000
0   Ravi  22.0   Hyderabad    Male   85.0   30000
4   Ravi  22.0   Hyderabad    Male   85.0   30000
2  Arjun  21.0   Hyderabad    Male   76.0   28000
1   Sita  24.0     Kurnool  Female   92.0   35000
7   Sita  24.0     Kurnool  Female   92.0   35000
5  Kiran  23.0     Kurnool    Male    NaN   32000
3  Priya  25.0  Vijayawada  Female   88.0   40000
9    NaN  25.0         NaN  Female   80.0   31000

In [110]:
#  sort index --> sorts according to row index
df.sort_index(ascending=False)

    Name   Age        City  Gender  Marks  Salary
9    NaN  25.0         NaN  Female   80.0   31000
8  Rahul  26.0      Guntur    Male   67.0   27000
7   Sita  24.0     Kurnool  Female   92.0   35000
6    Anu   NaN      Guntur  Female   95.0   45000
5  Kiran  23.0     Kurnool    Male    NaN   32000
4   Ravi  22.0   Hyderabad    Male   85.0   30000
3  Priya  25.0  Vijayawada  Female   88.0   40000
2  Arjun  21.0   Hyderabad    Male   76.0   28000
1   Sita  24.0     Kurnool  Female   92.0   35000
0   Ravi  22.0   Hyderabad    Male   85.0   30000

In [111]:
#  largest and smallest
#  nlargest()
df["Marks"].nlargest(2)

6    95.0
1    92.0
Name: Marks, dtype: float64

In [114]:
#  nsmalest()
df["Marks"].nsmallest(3)

8    67.0
2    76.0
9    80.0
Name: Marks, dtype: float64

In [117]:
#  missing values() --> shows teuw where data is  missing
# df.isna()
# df.isnull()
#  count missing valules
df.isna().sum()
df.notna()
df.notna().sum()

Name       9
Age        9
City       9
Gender    10
Marks      9
Salary    10
dtype: int64

In [118]:
#  fiil na --> fill missing agwe with avg age.
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    Name        Age        City  Gender  Marks  Salary
0   Ravi  22.000000   Hyderabad    Male   85.0   30000
1   Sita  24.000000     Kurnool  Female   92.0   35000
2  Arjun  21.000000   Hyderabad    Male   76.0   28000
3  Priya  25.000000  Vijayawada  Female   88.0   40000
4   Ravi  22.000000   Hyderabad    Male   85.0   30000
5  Kiran  23.000000     Kurnool    Male    NaN   32000
6    Anu  23.555556      Guntur  Female   95.0   45000
7   Sita  24.000000     Kurnool  Female   92.0   35000
8  Rahul  26.000000      Guntur    Male   67.0   27000
9    NaN  25.000000         NaN  Female   80.0   31000

In [119]:
# fill with fixed value()
df["Age"] = df["Age"].fillna(0)
df

    Name        Age        City  Gender  Marks  Salary
0   Ravi  22.000000   Hyderabad    Male   85.0   30000
1   Sita  24.000000     Kurnool  Female   92.0   35000
2  Arjun  21.000000   Hyderabad    Male   76.0   28000
3  Priya  25.000000  Vijayawada  Female   88.0   40000
4   Ravi  22.000000   Hyderabad    Male   85.0   30000
5  Kiran  23.000000     Kurnool    Male    NaN   32000
6    Anu  23.555556      Guntur  Female   95.0   45000
7   Sita  24.000000     Kurnool  Female   92.0   35000
8  Rahul  26.000000      Guntur    Male   67.0   27000
9    NaN  25.000000         NaN  Female   80.0   31000

In [128]:
df.sort_values("City",ascending=False).tail(3)

    Name        Age    City  Gender  Marks  Salary
6    Anu  23.555556  Guntur  Female   95.0   45000
8  Rahul  26.000000  Guntur    Male   67.0   27000
9    NaN  25.000000     NaN  Female   80.0   31000

In [131]:
df.sort_values("City",ascending=False).head(3)

    Name   Age        City  Gender  Marks  Salary
3  Priya  25.0  Vijayawada  Female   88.0   40000
1   Sita  24.0     Kurnool  Female   92.0   35000
5  Kiran  23.0     Kurnool    Male    NaN   32000

In [134]:
df.sort_values("City",ascending=False).iloc[0:2,1:3]
df.sort_values("City",ascending=False).loc[:,["Marks","City"]]

   Marks        City
3   88.0  Vijayawada
1   92.0     Kurnool
5    NaN     Kurnool
7   92.0     Kurnool
0   85.0   Hyderabad
2   76.0   Hyderabad
4   85.0   Hyderabad
6   95.0      Guntur
8   67.0      Guntur
9   80.0         NaN